### ISSUE TITLE
If the apply button over a note node it's not working

### ISSUE THREAD

**Issue by AntoineCharton** [ConstellationLanguage/Constellation#39]

**Comment by nupsi** [comment]
For me it works when clicked with middle/right click but not with left click. 

This seems to be similar problem that remove link button had. Current fix for button over node in [LinkView.cs](https://github.com/ConstellationLanguage/Constellation/blob/1c7fcf2d2e6c76f55a4053e64a29e6fc942de10b/Constellation/Assets/Constellation/Editor/NodeEditor/LinkView.cs) lines 86-99. But it's not efficient way to fix the problem.

**Comment by AntoineCharton** [comment]
Hey nupsi!

I have created a refactoring editor channel to find a good way to fix those bugs. If you have some time I would like to have your opinion on it :)

**Comment by AntoineCharton** [comment]
Fixed with the refactored version of the editor
