### ISSUE TITLE
Clarifying what the help button does

### ISSUE THREAD

**Issue by marcosecchi** [ConstellationLanguage/Constellation#61]
**Repro**:

1. Create a node
2. Rollover on it to show buttons
3. Click on the manual button ("?")
4. Instead of showing the documentation, the game starts

**Additional info**:

Tested on _macOS 10.13.15: and _Unity 2018.1.4f1_

**Comment by AntoineCharton** [comment]
Hi marcosecchi. When you click the ? button  the expected behavior is that it opens an example scene with the node that you need help with.

[Is this the behaviour your are having?](https://cdn.discordapp.com/attachments/406257842614566912/429831150853160960/Examples.gif)

**Comment by marcosecchi** [comment]
Hello @AntoineCharton, thanks for clarifying. Yes that's exactly what happens... I guess I misinterpreted the behaviour.

You can safely close this issue,

**Comment by AntoineCharton** [comment]
Hi @marcosecchi. 

I renamed the issue. It's not a bug but I agree it might be confusing. So what I'm thinking to do is the help button will open the example constellation without playing. The tutorial node will have a run button that will need to be pressed before entering play mode. What do you think?

**Comment by marcosecchi** [comment]
@AntoineCharton that would be a great idea! Not sure though if the help button should open a web page with a reference (manual or similar).

**Comment by AntoineCharton** [comment]
Why not for the reference. I've open an other [issue](https://github.com/ConstellationLanguage/Constellation/issues/62) for that. This one is more an enhancement. Implementing a reference is a new feature.

**Comment by marcosecchi** [comment]
Good, Thanks!
