### ISSUE TITLE
Node Editor Errors

### ISSUE THREAD

**Issue by TheophileBlard** [ConstellationLanguage/Constellation#69]
Hi, I keep running on these errors when I open the editor :

![error1](https://user-images.githubusercontent.com/37028092/43602078-325531a0-968f-11e8-85fc-527a08ff785e.png)
![error2](https://user-images.githubusercontent.com/37028092/43602084-35fa85c6-968f-11e8-9d5f-2357c1e49267.png)

The first one pops up randomly when I open the Node Editor (sometimes not on the first time).
And after the first one shows up once, I get the other one even without opening the Node Editor.

I'm using the last version on the Asset Store, and Unity 2018.2.0f2.

**Comment by AntoineCharton** [comment]
Thanks for the report I'm on it. 

I've never had this issue. Can you tell me what action you did before you had those errors?

One quick fix you could do is deleting the editorData.asset file (Assets/Constellation/Editor/EditorData)

**Comment by AntoineCharton** [comment]
That very usefull info and very good feedback. The popup is a Unity error but if Constellation is the cause I will fix ASAP. 

>I have a system that automaticaly create an delete ConstellationScript and assign them to a field in another ScriptableAsset.

First gess (I might be wrong) the delete ConstellationScript is probably what's causing the issue. Do you call [AssetDatabase.Refresh](https://docs.unity3d.com/ScriptReference/AssetDatabase.Refresh.html) after deleting an asset file?

>I'm currently experiencing with a lot of new Nodes, modyfing them, deleting them etc.. I might modify/delete the code from a Node that is currently used in the NodeEditor.

That's something that I want to support. If you encounter any issue while coding, please report them. I will fix those. 
Here is what you should expect. 
- Modify  shouldn't be an issue. You might loose links connections but normally you shouldn't have an error. 
- Delete will probably cause an error on runtime. I didn't thought of it but I will add it on next fix. No promises but if I have some time this week-end it should be live next tuesday.
- Adding a new node shouldn't be a problem either.

Thanks

**Comment by TheophileBlard** [comment]
So... Deleting randomly the ConstellationScripts doesn't seem to be the problem, even without refreshing the AssetDatabase properly.

I know that the `Inconsistency detected` error is a Unity error, but it only showed up after the Constellation error, and it was the most annoying because it would show up event without working with Constellation. 

I think the problem is about changing the Nodes, because at that time I was experiencing a lot, changing file names, folders, namespaces, etc... But with a "normal" utilisation , I didn't experience any major issue (the Editor still throws a lot of random errors). I might be working on new Nodes next week, I'll be careful to write down what I'm doing so that you can maybe reproduce the bug. 

In the meantime, I just wanted to say I'm having a lot of fun with your asset, thanks !

**Comment by AntoineCharton** [comment]
> So... Deleting randomly the ConstellationScripts doesn't seem to be the problem, even without refreshing the AssetDatabase properly.

Ok no problem I will try to mess a bit with updating nodes to see if the error comes up. If you have a repro project that could be very helpful. My (second) gess is Constellation is trying to load a deleted asset which somehow triggers an error somewhere. 

> I think the problem is about changing the Nodes, because at that time I was experiencing a lot, changing file names, folders, namespaces, etc... But with a "normal" utilisation , I didn't experience any major issue (the Editor still throws a lot of random errors)

Yes the editor is still unstable. I'm doing a refactoring so it can be more extendable for later features and more stable. Should be live for fall.  However I will push a fix this month so it's less unstable with the current version. The second thing is my error display definitelly needs more improvements. Next fix will show the error in the popup. 

> In the meantime, I just wanted to say I'm having a lot of fun with your asset, thanks !

Thanks a lot! You are one of the first users so sorry if there is some anoying/basics bugs in it. Just to let you know it's very usefull for me to have feedback. It's the best way for me to find issues and fix them and improve the framework.

**Comment by TheophileBlard** [comment]
Hey, I've had this bug again, as expected. I didn't do much, just deleted an input from a Node.
But I might have find something : somehow there were two editorData.asset files in the library.

![double](https://user-images.githubusercontent.com/37028092/43677557-f7dbe5a2-9803-11e8-9bd7-427c397cdf5e.png)

Deleting them both didn't solve the issue, I still had to quit the project and reload all the assets.

**Comment by AntoineCharton** [comment]
Oh ok that's interesting Editor data should definitelly not be created twice.  Let me see if I can see why this happen

**Comment by AntoineCharton** [comment]
Hello can you try this [fix](https://github.com/ConstellationLanguage/Constellation/releases/download/0.6f2/Constellation0.6f2.unitypackage) and tell me if it's better?

Just be carefull with it the code was not tested a lot (Make a backup of your project). 

Changes: 
- uknown errors always print a stack trace in the console. 
- If a node namespace or code is removed the node is deleted in the constellation. 
- If an error is thrown editorData.asset is always deleted then readded to the project.

**Comment by TheophileBlard** [comment]
Thank you for the fix, but it does not solve the problem.
I can't say if it's exactly the same problem because I still can't figure what are the exact steps.
You fix is still better than before, when the bug occure, Unity crash almost immediatly and I don't have the "Inconstency" error.

**Comment by AntoineCharton** [comment]
Is it the constellation window that crash or unity?

Normally when a constellation error occurs you should see some errors in the unity console. Can you post them? It will help me know exactly where the issue is.

**Comment by TheophileBlard** [comment]
I can't see any message, because I keep on getting Constellation error popups, and after a bunch of them (randomly clicking between "recover" or quit) the Unitor Editor crash.

The steps led me to the error, but I didn't reproduce them to verifiry it's always problematic (don't want to loose too much time) : 
1 - I created a Node (in my own namespace), went to the Constellation Editor, but I forgot to add the Node to the Factory.
2 - I closed the Constellation Editor window, went back to my code I added the Node to the Factory.
3 - I opened up the Constellation Editor again; and it crashed.

By the way, you should add some specific error handling for when you forget to add a Node to the Factory and click on it in the editor.

**Comment by AntoineCharton** [comment]
Thanks for the repro it's a start. I will check it tonight.

Yes I will add a specific error that won't crash the editor.

**Comment by AntoineCharton** [comment]
Hello,

I have a new version. If you can just use it as you do normally and just post the logs folder here that will help me a lot. (EditorData/Logs)

(https://github.com/ConstellationLanguage/Constellation/releases/download/0.6f2/Constellation0.6f3.unitypackage)

Here are the changes:
- Node not added in a factory will have its own error (Can be ignored without refreshing the editor)
- Added a log file which will write a log file in EditorData/Logs. 

Thanks a lot for the time you take. I know it's a bit frustrating but your feedback is helping so much ;).

**Comment by AntoineCharton** [comment]
Closing the issue since asset database is not corrupted anymore. If you find more errors feel free to open an other issue
