### ISSUE TITLE
Unknow Error from: ConstellationUnityWindow (0) 

### ISSUE THREAD

**Issue by zak-35** [ConstellationLanguage/Constellation#70]
Hello,
I just downloaded Constellation today. When I created a script and chose to open it in the node editor. This also happens when I open the editor through window>Constellation>Editor. This is the message it gave me:
![screen shot 2018-10-03 at 4 37 00 pm](https://user-images.githubusercontent.com/43832747/46445241-9c526700-c72a-11e8-9eed-ed005b6447d5.png)
When ever this happens it freezes Unity so I can't click on anything out of the popup window. When I click recover there is a large glitched box that covers a portion of the screen. (See Below)
![screen shot 2018-10-03 at 4 40 18 pm](https://user-images.githubusercontent.com/43832747/46445322-0c60ed00-c72b-11e8-9bb2-00b901fcf7ac.png)
Also it said something in the console. I think it said that there was an error finding Editor File. I then decided to re download Constellation to no avail. 
I could just be doing something wrong, but I do not know what. I tried looking up how to use Constellation, but I couldn't find anything. I'm using 2017.4
Thanks for any help.

**Comment by AntoineCharton** [comment]
Ok nice thanks a lot nupsi I will check it

**Comment by AntoineCharton** [comment]
Refactored editor fixed in next release
